
import { UserRank } from './types';

export const START_DATE = new Date(2026, 1, 15); 
export const EXAM_DATE = new Date(2026, 1, 24, 9, 0, 0); 

export const MOTIVATIONAL_THOUGHTS = [
  "Time is the scarcest resource in the Wprime protocol.",
  "80 marks require 80 units of absolute discipline.",
  "The clock is either your partner or your executioner.",
  "Every journal entry skipped today is a mark lost on Feb 24.",
  "Time is non-refundable. Spend it on your ledger.",
  "Mr. Piyush built this for those who value minutes.",
  "Excellence is not an act, but a habit of time management.",
  "Don't count the days, make the days count.",
  "Your future self is watching you through the clock.",
  "A minute of planning saves an hour of error-correction.",
  "Wprime logic: Time > Excuses.",
  "Balance your life as precisely as you balance your T-accounts.",
  "Focus is the art of saying 'no' to time-wasters.",
  "The 9-day grind is a test of your character, not just memory.",
  "You cannot manage time, you can only manage yourself within it.",
  "The best preparation for tomorrow is doing today's work today.",
  "Consistency is the compound interest of learning.",
  "An hour of deep work is worth five hours of distraction.",
  "Time is what we want most, but what we use worst.",
  "Discipline is the bridge between goals and accomplishment.",
  "The only difference between a dream and a goal is a deadline.",
  "Feb 24 is coming. Will you be ready?",
  "A paper solved today is a fear conquered tomorrow.",
  "Audit your own time before the examiner audits your paper.",
  "Time is free, but it's priceless.",
  "The grind never lies. The results never lie.",
  "9 days. 216 hours. Use every single one.",
  "Success is the sum of small efforts repeated daily.",
  "Your competition is solving papers while you read this.",
  "Be obsessed with the 80/80 target.",
  "Procrastination is the thief of time.",
  "Do it now. 'Later' often becomes 'Never'.",
  "Hard work beats talent when talent doesn't work hard.",
  "The only place success comes before work is in the dictionary.",
  "There are no shortcuts to any place worth going.",
  "Wprime Protocol: Precision. Focus. Speed.",
  "Don't stop when you're tired, stop when you're done.",
  "You are one paper away from a different level of confidence.",
  "Time flows like cash. Don't waste it on bad investments.",
  "Sacrifice the now for the forever.",
  "The pain of discipline is less than the pain of regret.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Motivation gets you started. Habit keeps you going.",
  "You don't get what you wish for, you get what you work for.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Dream it. Believe it. Build it. Wprime it.",
  "Stay focused. Stay humble. Work hard.",
  "Success is not for the lazy.",
  "Work hard in silence, let your 80/80 be the noise.",
  "Difficult roads lead to beautiful destinations.",
  "Don't wait for opportunity. Create it.",
  "Sometimes later becomes never. Do it now.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Start where you are. Use what you have. Do what you can.",
  "The secret of getting ahead is getting started.",
  "It always seems impossible until it's done.",
  "If you want to fly, give up everything that weighs you down.",
  "Your time is limited, don't waste it living someone else's life.",
  "Believe you can and you're halfway there.",
  "Everything you've ever wanted is on the other side of fear.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The way to get started is to quit talking and begin doing.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is not final; failure is not fatal: it is the courage to continue that counts.",
  "Don't be afraid to give up the good to go for the great.",
  "The starting point of all achievement is desire.",
  "Opportunities don't happen. You create them.",
  "The distance between insanity and genius is measured only by success.",
  "The secret to success is to know something nobody else knows.",
  "I never dreamed about success, I worked for it.",
  "Action is the foundational key to all success.",
  "The only way to do great work is to love what you do.",
  "If you can dream it, you can do it.",
  "Work like there is someone working 24 hours a day to take it away from you.",
  "Fall seven times, stand up eight.",
  "Quality is not an act, it is a habit.",
  "The harder the conflict, the more glorious the triumph.",
  "Well begun is half done.",
  "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward.",
  "A year from now you may wish you had started today.",
  "You miss 100% of the shots you don't take.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "Efficiency is doing things right; effectiveness is doing the right things.",
  "The goal is not to be better than the other man, but your previous self.",
  "Either you run the day or the day runs you.",
  "Today is your opportunity to build the tomorrow you want.",
  "The future depends on what you do today.",
  "Don't let yesterday take up too much of today.",
  "Wprime: Forged in the fires of late-night study.",
  "Accountancy is the language of business. Speak it fluently.",
  "Every variance analysis brings you closer to 100% accuracy.",
  "Audit your habits before you audit your books.",
  "Goodwill is earned by the hours you put in now.",
  "Liquidity of time is your most valuable asset.",
  "Depreciation of knowledge happens without constant revision.",
  "Feb 15 - Feb 23: The most important 9 days of the year.",
  "Wprime is your final filter for excellence.",
  "Mr. Piyush built this. You execute it. 80/80."
];

export const MOTIVATIONAL_QUOTES = MOTIVATIONAL_THOUGHTS.slice(0, 10);

export const generateDefaultSessions = (day: number, date: Date) => [
  {
    id: `d${day}-p1`,
    title: 'Paper Execution Protocol',
    duration: '3.5 Hours',
    completed: false,
    tasks: [
      { id: `d${day}-p1-t1`, label: 'Solve Full Sample Paper / PYP', completed: false },
    ]
  }
];

export const RANKS = [
  { threshold: 0, name: UserRank.BEGINNER, icon: '🌱' },
  { threshold: 500, name: UserRank.FOCUSED, icon: '🎯' },
  { threshold: 1500, name: UserRank.CONSISTENT, icon: '🔥' },
  { threshold: 3000, name: UserRank.EXAM_READY, icon: '🏅' },
];
